name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run go fmt
        run: go fmt ./...

      - name: Run go vet
        run: go vet ./...

      - name: Run unit tests with coverage
        run: go test ./... -coverprofile=coverage.out

      # ---------- E2E Setup ----------
      - name: Set up kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: kind

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.30.0

      - name: Install cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.yaml
          kubectl rollout status deployment/cert-manager -n cert-manager --timeout=120s || true
          kubectl rollout status deployment/cert-manager-webhook -n cert-manager --timeout=120s || true

      - name: Build Docker image
        run: |
          docker build -t auto-mtls:latest .

      - name: Load image into kind
        run: kind load docker-image auto-mtls:latest --name kind

      - name: Deploy manifests
        run: |
          kubectl apply -f config/deploy/

      - name: Run e2e tests
        run: go test ./test/e2e -v
